package br.view.Ongs;

import br.helpet.dao.PetDAO;
import br.view.TelaCadastro;
import br.view.Usuario.VerDenuncias;
import helpet.pojo.AdotarPets;
import helpet.pojo.Exemplo;
import helpet.pojo.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * @author Helpet
 */
public class TelaPrincipalOng extends javax.swing.JFrame {

    long cnpj;
      
    public TelaPrincipalOng() {
        initComponents();
        
    }
    
 public TelaPrincipalOng(long cnpj) {
     initComponents();
     this.cnpj = cnpj;
        
        System.out.println(cnpj);
        
        DefaultTableModel modelo = (DefaultTableModel) jTableSoli.getModel();															
        jTableSoli.setRowSorter(new TableRowSorter(modelo));
        
        DefaultTableModel modelo1 = (DefaultTableModel) jTablePetsDoa.getModel();															
        jTablePetsDoa.setRowSorter(new TableRowSorter(modelo1));
     	
        readJtable();
        readJtable1();
    }

public void readJtable(){																								
        DefaultTableModel modelo = (DefaultTableModel) jTableSoli.getModel();														
        modelo.setNumRows(0);																								
        PetDAO petdao = new PetDAO();																					
        																												
        for(AdotarPets f: petdao.listarPetsSolicitados(cnpj)){																						
           modelo.addRow(new Object[]{																						
           f.getId_usu(),
           f.getId_petDoa()
           });
        }																												
    }
public void readJtable1(){																								
        DefaultTableModel modelo1 = (DefaultTableModel) jTablePetsDoa.getModel();														
        modelo1.setNumRows(0);																								
        PetDAO petdao = new PetDAO();																					
        																												
        for(Exemplo f: petdao.listarPetsAdocaoLogado(cnpj)){																						
           modelo1.addRow(new Object[]{																																															
           f.getApelido(),
           f.getDescricao()
           });
        }																												
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jButtoncadpetdoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePosts = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePetsDoa = new javax.swing.JTable();
        jTextFieldPesquisarWiki = new javax.swing.JTextField();
        jButtonbuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSoli = new javax.swing.JTable();
        jTextFieldIdUsu = new javax.swing.JTextField();
        jTextFieldpet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadPets = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtoncadpetdoa.setText("cadastrat pet doação");
        jButtoncadpetdoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadpetdoaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncadpetdoa);
        jButtoncadpetdoa.setBounds(10, 290, 159, 29);

        jTablePosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Veterinário", "Titulo", "Descrição"
            }
        ));
        jTablePosts.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTablePostsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTablePosts);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 110, 500, 320);

        jTablePetsDoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nome", "tipo", "descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablePetsDoa);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 380, 170);
        getContentPane().add(jTextFieldPesquisarWiki);
        jTextFieldPesquisarWiki.setBounds(540, 0, 170, 27);

        jButtonbuscar.setText("buscar");
        jButtonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonbuscar);
        jButtonbuscar.setBounds(710, 0, 59, 29);

        jTableSoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código do solicitante", "Código Pet Solicitado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableSoli);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 330, 380, 190);

        jTextFieldIdUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdUsuActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdUsu);
        jTextFieldIdUsu.setBounds(20, 550, 150, 27);
        getContentPane().add(jTextFieldpet);
        jTextFieldpet.setBounds(190, 550, 160, 27);

        jButton1.setText("Conceder Adoção");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 580, 150, 40);

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 290, 90, 20);

        jLabel6.setText("Pet Desejado");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 530, 100, 20);

        jLabel5.setText("Código do solicitante");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 530, 145, 17);

        jLabel4.setText("Pets para adoção");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 80, 150, 17);

        jLabel3.setFont(new java.awt.Font("URW Bookman L", 3, 18)); // NOI18N
        jLabel3.setText("Bem-Vindo!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 130, 30);

        jLabel2.setText("Pesquisa:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 0, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Alien_Ink_2560X1600_Abstract_Background_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1160, 770);

        jMenuBar1.setBackground(new java.awt.Color(8, 0, 104));
        jMenuBar1.setForeground(new java.awt.Color(1, 12, 53));

        jMenuCadastros.setBackground(new java.awt.Color(60, 59, 55));
        jMenuCadastros.setForeground(new java.awt.Color(223, 219, 210));
        jMenuCadastros.setText("Cadastrar ");

        jMenuItemCadPets.setText("Conta");
        jMenuItemCadPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPetsActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadPets);

        jMenuItem11.setText("pets doação");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem11);

        jMenuBar1.add(jMenuCadastros);

        jMenu1.setText("Achados e perdidos");

        jMenuItem5.setText("Achados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Perdidos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Denuncias");

        jMenuItem8.setText("Ver Denuncias");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Sair");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("atualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1169, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPetsActionPerformed
        TelaCadContaOng cadP = new TelaCadContaOng(cnpj);
        cadP.setVisible(true);     

    }//GEN-LAST:event_jMenuItemCadPetsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         if (JOptionPane.showConfirmDialog(null,"Deseja sair?")==JOptionPane.OK_OPTION){
             dispose(); 
             TelaCadastro tc = new TelaCadastro();
             tc.setVisible(true);
         }    
        
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTablePostsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTablePostsAncestorAdded
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTablePostsAncestorAdded

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        VerDenuncias vd = new VerDenuncias();
        vd.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButtonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuscarActionPerformed
  
    }//GEN-LAST:event_jButtonbuscarActionPerformed

    private void jButtoncadpetdoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadpetdoaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtoncadpetdoaActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        EnviarImagem AP = new EnviarImagem(cnpj);
        AP.setVisible(true);
       
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jTextFieldIdUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdUsuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario u = new Usuario();
        AdotarPets ap = new AdotarPets();
        PetDAO pdao= new PetDAO();
        
        u.setId_usuT(Integer.parseInt(jTextFieldIdUsu.getText()));
        u.setId_pet_adotado(Integer.parseInt(jTextFieldpet.getText()));
        
        ap.setId_usu(Integer.parseInt(jTextFieldIdUsu.getText()));
        ap.setId_petDoa(Integer.parseInt(jTextFieldpet.getText()));
        
        
        try {
            pdao.updatePetsAdocao(u);
            pdao.removerTabelaDeSolicitacao(ap);
            readJtable();

        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipalOng.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        readJtable();
        readJtable1();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalOng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonbuscar;
    private javax.swing.JButton jButtoncadpetdoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemCadPets;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePetsDoa;
    private javax.swing.JTable jTablePosts;
    private javax.swing.JTable jTableSoli;
    private javax.swing.JTextField jTextFieldIdUsu;
    private javax.swing.JTextField jTextFieldPesquisarWiki;
    private javax.swing.JTextField jTextFieldpet;
    // End of variables declaration//GEN-END:variables
}
