package br.view.Usuario;

import br.helpet.dao.UsuariosDAO;
import helpet.pojo.Denuncias;

/**
 * @author Helpet
 */
public class TelaCadDenuncia extends javax.swing.JFrame {

    int id_usuD;
    
    public TelaCadDenuncia(int id_usu) {
        this.id_usuD= id_usu;
        initComponents();
    }
    public TelaCadDenuncia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescri = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldcity = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 144, 144));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("CADASTRE SUA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 130, 30);

        jLabel2.setText("Titulo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 180, 44, 17);
        jPanel1.add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(60, 200, 400, 27);

        jLabel3.setText("Descrição:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 230, 73, 17);

        jTextAreaDescri.setColumns(20);
        jTextAreaDescri.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescri);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 250, 400, 158);

        jLabel4.setText("Local");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 420, 37, 17);

        jLabel5.setText("Rua:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 430, 29, 17);

        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 480, 52, 17);

        jLabel7.setText("cidade:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 480, 50, 17);
        jPanel1.add(jTextFieldRua);
        jTextFieldRua.setBounds(60, 450, 400, 27);
        jPanel1.add(jTextFieldcity);
        jTextFieldcity.setBounds(270, 500, 190, 27);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Escolha o estado", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA) ", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));
        jPanel1.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(60, 500, 190, 27);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 530, 80, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teste1denun_2.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 10, 490, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-clean1.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 10, 480, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(533, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UsuariosDAO u = new UsuariosDAO();
        Denuncias d = new Denuncias();
        
        d.setDescricao(jTextAreaDescri.getText());
        d.setTitulo(jTextFieldTitulo.getText());
        d.setCidade(jTextFieldcity.getText());
        d.setRua(jTextFieldRua.getText());
        d.setEstado((String)jComboBoxEstado.getSelectedItem());
        d.setId_usuD(id_usuD);
        u.adicionarDenuncias(d);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadDenuncia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescri;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldcity;
    // End of variables declaration//GEN-END:variables
}
